### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by SlenderSolo** [pierre-picard/minibot#10]
I started getting these crashes 4 days ago and am getting them ever since. I farm 8 sessions and 10-15 minutes after launch I get the first crash, after the windows crash every 10-15 minutes. I tried to turn off addons, check game files, reinstall wow, reinstall windows, update drivers, completely turn off the defender, download clean minibot with a standard profile, did not use custom actions or variables in scripts, none of this helped me.
Specs
Ryzen 3600
RX 5700 XT
B450
Windows 10 Enterprise 20H2 19042.804 
<img width="309" alt="Screenshot_1" src="https://user-images.githubusercontent.com/55142604/107830156-4da64480-6d9c-11eb-8b80-4cd3c43d9ac2.png">

**Comment by Druxlolz** [comment]
We are in the same boat bro, pretty much every 5-15min here crash no matter what tried all above and also bios update.

**Comment by pierre-picard** [comment]
This issue is most likely to be a result of the new Windows patches with the latest ZEN 3 architecture, as it only starts to appear recently while it has been all good over the past years. We are still investigating without ETA, and you can try revert to old Windows versions meanwhile.

**Comment by pierre-picard** [comment]
To follow up this case, our techs have managed to support the lastest ZEN-3 architecture in a perfect sense. So this case is totally finalized.
