### ISSUE TITLE
Feature request. custom wow exe`s names.

### ISSUE THREAD

**Issue by Devanse7** [pierre-picard/minibot#14]
Good day. Since its not safe to run 3+ wow`s on same IP, we need custom wow exe names to use proxicap or proxifier and create custom rules for each exe. Atm its not possible because minibot use same exe for every seesion
We need smng like :

Session 1 : c/wow/wow1.exe
Session 2 c/wow/wow2.exe 
etc.

Many tnx!

**Comment by pierre-picard** [comment]
This can be arranged via a simple new launch option: "Match any game program file of the same version instead".

**Comment by Devanse7** [comment]
or attach to any wow*.exe

**Comment by pierre-picard** [comment]
There is no "attach" concept. This is the only solution. So whatever name you open after launch will be injected until the session count is reached.

**Comment by Devanse7** [comment]
sounds great for me :)

**Comment by pierre-picard** [comment]
Please upgrade your client to v1.3.5 and you will see:
1. The GUI version has a new launch option to match any game program file name.
2. The CLI version "inject" verb also has a new launch option called "match-any-game-file".

**Comment by Devanse7** [comment]
tested. Works perfect. /bow

**Comment by maximnaro** [comment]
Can we also expand this for classic & retail? So we can start classic and retail? Right now only same game version works

**Comment by pierre-picard** [comment]
No. You can only choose one game version per launch.
