### ISSUE TITLE
I get an error when using a multiprocessor.

### ISSUE THREAD

**Issue by DisplayPort1** [pierre-picard/minibot#15]
I get an error when using a multiprocessor.
I know this is a common problem when an application cannot work with a multiprocessor. Any Windows system gives the same error. If I use the same settings but on a laptop, everything works. I've tried every possible way. But the minibot could not start. I'm sure the problem is related to the fact that the minibot is not configured to work with multiprocessor systems.
[error 515]
my system xeon 5675 (two processors)

can you add multiprocessor support to your program? 2 and more...?

**Comment by DisplayPort1** [comment]
or ЕСС

**Comment by pierre-picard** [comment]
Error 515 means our technology cannot be initialized correctly on your system. It may be your BIOS settings or hardware incompatibility. In either way, we can't help due to technology limitations.

**Comment by DisplayPort1** [comment]
One way or another, the same error was with the amd processors. But you added support. And wait for optimization for highly reliable RAM?
