### ISSUE TITLE
UnitNPCFlags

### ISSUE THREAD

**Issue by idkwhoiam906** [pierre-picard/minibot#16]
"UnitNPCFlags": 

Its a flag on each npc WowUnit that specifies what type of NPC it is. 

both ewt / luabox called them NPCFlags as do all the private servers.

Honorbuddy used to call them the same: 
http://docs.honorbuddy.com/html/3b416106-5e4d-0e1c-de4a-b1415d1d01a9.htm

It should just be another int on the unitclass. They likely already have it exposed internally.

**Comment by pierre-picard** [comment]
Enumerate the descriptors table and you will find all useful values like this one. Call ```ObjectDescriptor``` to grab the value needed.

On Classic, the descriptor table is full as game memory contains it. It is called ```CGUnitData__npcFlags```.
On Retail, we didn't provide this one as each of them is added manually. Will arrange this work in near future.

**Comment by idkwhoiam906** [comment]
I need this for Retail. We tried what you said but the information we need is not displayed. I understand that you say you will add it in the near future so I will wait. Thank you

**Comment by pierre-picard** [comment]
```CGUnitData__npcFlags``` has been added to ```GetObjectDescriptorsTable()``` on Retail, just like Classic. So you can get the offset and call ```ObjectDescriptor()``` to get the relevant value.
