### ISSUE TITLE
Encrypted scripts limit

### ISSUE THREAD

**Issue by maximnaro** [pierre-picard/minibot#17]
Right now when someone who has 2 sessions opens a script which is limited to 1 session he cant open it as it will say that he is not allowed to use it based on his session count. Can we somehow add anything to limit scripts on usage eventho the person might have more sessions in general?

**Comment by pierre-picard** [comment]
The system built-in authorization only prevents the script from being loaded if the launched sessions exceed the limit. If you are not satisfied with the simple solution, you could always go the "hard & customized" way like many other vendors do to create your own Lua-based custom authorization system, usually based on your own web API.
