### ISSUE TITLE
Feature Request: Configurable "costs/weights" for each nav type. 

### ISSUE THREAD

**Issue by fusspawn** [pierre-picard/minibot#18]
I want to be able to configure navigator (and thus recast / detour) with custom weights for each polygon flag type. 
Ie land could be configured to cost 1 /unit per yard. water 2/units per yard ect. 

Would allow nav to generate the actual "fastest" path. and not just the shortest path. 

Ideally would allow being able to configure it for all pre existing and custom flags set via SetMeshPolygonFlags(). 

Something like.
SetCustomNavWeights({1= 1.5,  2= 2.5, 4= 999,  32= 0})

**Comment by pierre-picard** [comment]
Job is done: https://github.com/pierre-picard/minibot/commit/95ec514605fa9ff8602ce1ef97d5acfdf46abdad
