### ISSUE TITLE
Does not work in a VM on an Intel Core i9-10850k processor

### ISSUE THREAD

**Issue by SpyBotting** [pierre-picard/minibot#20]
Is it possible to fix the support of the minibot in the VM for the i9-10850k processor. When running on a VM, the guest windows goes into a reboot. There is also a familiar with the same problem on this processor. I can say with confidence that there are no such problems on the i7-8700k processor and the minibot works on a VM.

**Comment by pierre-picard** [comment]
If you can run the system on the physical machine, there is no way for us to fix anything for VM, as we don't offer any guarantee for VM.

**Comment by SpyBotting** [comment]
> If you can run the system on the physical machine, there is no way for us to fix anything for VM, as we don't offer any guarantee for VM.

Everything works on the physical machine, but using a lot of sessions on the physical machine puts them at risk of blocking if at least one of them is detected. It is strange that everything works on the younger generation of Intel processors and fewer cores. There are thoughts that the mini-bot does not work with Intel processors where there are 8 cores or more, it is in a virtual environment, because the same problem is observed on Xeon 2678v3,2640v3, 2667v2 processors, despite the fact that everything is OK on the physical machine, the virtual one goes into a reboot.
