### ISSUE TITLE
Feature Request: World Preload

### ISSUE THREAD

**Issue by fusspawn** [pierre-picard/minibot#21]
Back on EWT We had a WorldPreload(MapId, x,y,z) function exposed that allowed us to load "distant" terrain physics data and be able to raycast against it where as minibot seems to always return no collision past a certain range.

I'm not sure how it worked internally. but it would throw up a loading screen like a zone change for a split second.  Im fairly sure it was abusing the Spectator system somehow. 

We have a few automated scanner systems that could make use of this as well as doing longer distance path generation for flying mounts.

**Comment by pierre-picard** [comment]
Sorry, we are not familiar with any game engine rendering. This is not likely to be implemented.

**Comment by fusspawn** [comment]
I'm not sure i understand your response.

This has little if any relation to rendering. Its about loading physics data outside the range of what wow does by default. I dont care about having it rendered. I want to be able to trace line against it and not just have it always fail because its outside of the range the client usually loads physics data.

**Comment by pierre-picard** [comment]
How game engine handles terrain means rendering. Anyway, we have 0 knowledge about any 3D game engine related stuffs.
