### ISSUE TITLE
Problem with launch of multiple sessions

### ISSUE THREAD

**Issue by olejenek1000** [pierre-picard/minibot#22]
I start 1 session and another one gets an error
how to run correctly to avoid this error?
he thinks that I have 7 running but I have 6 running and when I run the seventh which 1 crashes why is that?
and to start 7 again, I need to close all minibots and start again one at a time. It takes a lot of time.
so I started the seventh session and one flew out of me
This happens if I started 7 sessions, then I closed 1 session to restart it and crashes on one of the 6 remaining sessions.
He thinks that I have 7 sessions running, so an error occurs
because of this, I need to close all sessions, reboot the computer and restart 1 session at a time so that there is no error and it takes a lot of time.
Error: The current session is no longer available, as it appears your system account has been logged in from a different pc.

**Comment by pierre-picard** [comment]
1. On one PC, sessions are fixed when you launch. And you can't re-launch before all sessions are consumed and closed.
2. On multiple PCs, you need to wait 10 min after sessions are closed before you can re-use them. Or you are risking kicking other non-closed sessions.

This is not a support place. Contact your seller about how to use sessions in more details.

**Comment by olejenek1000** [comment]
I use 10 virtual machines and I have 1 minibot account with 10 sessions. If I run 10 sessions on 10 virtual machines for the first time, everything will work. But there are times when you need to close 1 session on the virtual machine and 9 sessions remain working. When I restart the tenth session, one and 9 sessions crashes with an error. If your decision to wait 10 minutes is not the best way why not take 1 minute? I want to buy 30 sessions for 1 account, but your mechanism stops me. I cannot close all sessions every time and then start them again or wait 10 minutes. Improve this moment please!

**Comment by pierre-picard** [comment]
If you wish hassle-free session usage (on-off without any trouble) on different machines, just purchase different MB accounts.

**Comment by olejenek1000** [comment]
Then I will need to activate only one session and the first session requires 15 credits. And it turns out not profitable and in general it is inconvenient to create 30 accounts

**Comment by olejenek1000** [comment]
make a normal solution to the problem please!

**Comment by pierre-picard** [comment]
The issue is already closed as is. You can contact any seller to create 30 accounts for you with ease. And that's the reason why the price is different.

**Comment by olejenek1000** [comment]
I buy from you 30 sessions for 30 days and do not receive any discounts, then why are there any discounts for those who activate the keys in one account? Why encourage some and discriminate against others? It is so stupid.

**Comment by olejenek1000** [comment]
And I don't close wow myself. You still have not solved the problem with disconnect and this happens 20-30 times a day, which increases the likelihood of the wow window hanging on the virtual machine.
