### ISSUE TITLE
Neither the GUI nor the CLI app are working

### ISSUE THREAD

**Issue by AllRange1337** [pierre-picard/minibot#23]
So I'm using Win10 
![image](https://user-images.githubusercontent.com/18470530/116810992-2ebb8100-ab47-11eb-8826-1407851d0731.png)
And have enabled Virtualization:
![image](https://user-images.githubusercontent.com/18470530/116811023-4e52a980-ab47-11eb-8d25-748008d9a2e3.png)
And made sure that Hyper-V is not installed and running .NET 4.8:
![image](https://user-images.githubusercontent.com/18470530/116811175-2283f380-ab48-11eb-8c42-136c7b42ef30.png)
I'm using a AMD Ryzen 7 4800H Processor.
And I deactivated Windows Defender.

I downloaded it via https://download.minitool.org/wow/patches/
When I launch the app nothing happens. No Gui no error nothing.
When launching the App with it's default name I get:
![image](https://user-images.githubusercontent.com/18470530/116811350-27957280-ab49-11eb-84fc-cbc53fe21829.png)

But after renaming nothing comes up or launches.

Also the link for the troubleshooting site doesn't work anymore.

**Comment by pierre-picard** [comment]
1. This is not a support place. Contact your seller. If you can't find one, join the channel and check the history notice.
2. You should always download the client from the seller. Nobody says that you should download from https://download.minitool.org/wow/patches/ which is obviously a patch and of course it wouldn't work.
