### ISSUE TITLE
about custom framework

### ISSUE THREAD

**Issue by txt1899** [pierre-picard/minibot#3]
1.how to use UI settings?
2.is it possible to extend the UI?
3.is there any special API for independent developers?

**Comment by pierre-picard** [comment]
Firstly, it is "project framework". And all your answers are located in the document. Please read carefully.

1. Search "custom settings" and you will find how you can add settings on the UI panel for your project.
2. All unlocker API is located in [API.md](https://github.com/pierre-picard/minibot/blob/master/API.md).
3. To repeat, please go to the telegram channel for more support.
