### ISSUE TITLE
about ObjectId

### ISSUE THREAD

**Issue by 1034063174** [pierre-picard/minibot#6]
print(wmbapi.ObjectId('mouseover'))   This method can't find door_id

use this way can  find   door_id

for i in pairs(myOM) do     -- myOM from wmbapi.GetObjectCount()
local X, Y, Z = wmbapi.ObjectPosition(i)
local dis2D = wmbapi.GetDistanceBetweenPositions(3623, -3642.5, 0, X, Y, 0)
if  (dis2D<=10)then
print (wmbapi.ObjectId(i))
end
end

**Comment by 1034063174** [comment]
i want to find  the door_ID and use  InteractUnit(door_ID ) open the door

**Comment by pierre-picard** [comment]
Find the object by its ID and pass the object to InteractUnit(object)

**Comment by 1034063174** [comment]
What I want to say is“ print(wmbapi.ObjectId('mouseover'))” Objects that cannot be selected are invalid

**Comment by pierre-picard** [comment]
"mouseover" is a BLZ keyword that only supports units, and only for your mouse units, As you are automating things with scripts, there is no point to use it, while you can always enumerate all game objects with GetGameObject API.
