### ISSUE TITLE
high performance drop since today

### ISSUE THREAD

**Issue by buloti** [pierre-picard/minibot#7]
Hi.
I managed to fix the VM Performance Drop last night and I could run all my session on different VM with no FPS drop. I tested for hours and rebooted VM and Game to be sure the problem is fixed, it was.
I shared with a friend and he did the same, problem fixed. But since today the performance drop is huge and it doesn't work anymore for him and for me. We didn't change anything since we fixed it last night So did you make a change the last 24h to Minibot?
The performance are even worse than before we had the fix.

here are the performance I had last night on all my vm with Vm with WOW + Minibot + Bot addons

Frames: 3600 - Time: 60000ms - Avg: 60.000 - Min: 44 - Max: 67

**Comment by pierre-picard** [comment]
We never change anything at such low level to affect your performance or everyone would have this issue. Also test on your physical machine without any script loaded. Please check for yourself as you did before.
