### ISSUE TITLE
disconnected 

### ISSUE THREAD

**Issue by 1034063174** [pierre-picard/minibot#8]
if EnableFlyingMode   and Get hit and fly， i will  get disconnected ， （NOT fallingr and  EnableFlyingMode  ）   
 i want to   attack monster  in sky ，but  The monster will fly me 。what can  i do  ？

**Comment by pierre-picard** [comment]
Read the API doc carefully. You should avoid flying while falling or you will get instant DC.

**Comment by 1034063174** [comment]
so ,if i want  to  attack  monster    , and monster can  fall/knockback me, i can‘t EnableFlyingMode 。
